import { describe, it, expect, beforeEach } from "vitest";
import { prisma } from "@/server/lib/prisma";
import { AppError } from "@/server/lib/errors";
import { resetDatabase } from "../helpers/db";
import { createDevice, createGate, createStaffUser, createStudent } from "../helpers/factories";
import { createStudentQrSession } from "@/server/modules/security/sessions.service";
import { getOrCreateExitCode } from "@/server/modules/security/exitCode.service";
import { verifyScan, verifyExit } from "@/server/modules/security/scan.service";

describe("Concurrency safety — the property the whole system depends on", () => {
  beforeEach(async () => {
    await resetDatabase();
  });

  it("under N simultaneous verifications of the SAME QR, exactly one succeeds and the rest are rejected as already-used", async () => {
    const officer = await createStaffUser();
    const gate = await createGate();
    const { device, rawSecret } = await createDevice(gate.id, officer.id);
    const student = await createStudent();

    const { qr } = await createStudentQrSession(student.id, "127.0.0.1");
    const scanInput = { qr, deviceIdentifier: device.deviceIdentifier, deviceSecret: rawSecret };

    const CONCURRENCY = 15;
    const outcomes = await Promise.allSettled(
      Array.from({ length: CONCURRENCY }, () => verifyScan(scanInput, officer.id, "127.0.0.1"))
    );

    const succeeded = outcomes.filter((o) => o.status === "fulfilled");
    const rejected = outcomes.filter((o) => o.status === "rejected");

    expect(succeeded).toHaveLength(1);
    expect(rejected).toHaveLength(CONCURRENCY - 1);

    for (const r of rejected) {
      if (r.status !== "rejected") continue;
      expect(r.reason).toBeInstanceOf(AppError);
      expect((r.reason as AppError).code).toBe("QR_ALREADY_USED");
    }

    // The database must reflect exactly one ENTRY — not zero, not many.
    const events = await prisma.accessEvent.findMany({ where: { studentId: student.id } });
    expect(events).toHaveLength(1);
    expect(events[0]!.eventType).toBe("ENTRY");

    const presence = await prisma.studentPresence.findUnique({ where: { studentId: student.id } });
    expect(presence?.status).toBe("INSIDE");
  });

  it("under simultaneous verifications of TWO DIFFERENT valid entry QRs generated by the same student and scanned at two different gates, exactly one ENTRY is recorded and the other is rejected as already-inside", async () => {
    const officer = await createStaffUser();
    const [gateA, gateB] = await Promise.all([createGate(), createGate()]);
    const { device: deviceA, rawSecret: secretA } = await createDevice(gateA.id, officer.id);
    const { device: deviceB, rawSecret: secretB } = await createDevice(gateB.id, officer.id);
    const student = await createStudent();

    const [{ qr: qrA }, { qr: qrB }] = await Promise.all([
      createStudentQrSession(student.id, "127.0.0.1"),
      createStudentQrSession(student.id, "127.0.0.1"),
    ]);

    const outcomes = await Promise.allSettled([
      verifyScan({ qr: qrA, deviceIdentifier: deviceA.deviceIdentifier, deviceSecret: secretA }, officer.id, "127.0.0.1"),
      verifyScan({ qr: qrB, deviceIdentifier: deviceB.deviceIdentifier, deviceSecret: secretB }, officer.id, "127.0.0.1"),
    ]);

    // The row lock on student_presence serializes the two transactions: whichever
    // commits first performs the ENTRY; the second — reading the now-updated
    // presence — is correctly rejected as ALREADY_INSIDE. Exactly one ENTRY, never two.
    const fulfilled = outcomes.filter((o) => o.status === "fulfilled");
    const rejected = outcomes.filter((o) => o.status === "rejected");
    expect(fulfilled).toHaveLength(1);
    expect(rejected).toHaveLength(1);
    if (rejected[0]!.status === "rejected") {
      expect(rejected[0]!.reason).toMatchObject({ code: "ALREADY_INSIDE" });
    }

    const events = await prisma.accessEvent.findMany({ where: { studentId: student.id } });
    expect(events).toHaveLength(1);
    expect(events[0]!.eventType).toBe("ENTRY");

    const presence = await prisma.studentPresence.findUnique({ where: { studentId: student.id } });
    expect(presence?.status).toBe("INSIDE");
  });

  it("under simultaneous self-service exits by the SAME student using the SAME permanent exit code, exactly one EXIT is recorded", async () => {
    const officer = await createStaffUser();
    const gate = await createGate();
    const { device, rawSecret } = await createDevice(gate.id, officer.id);
    const student = await createStudent();

    const { qr: entryQr } = await createStudentQrSession(student.id, "127.0.0.1");
    await verifyScan({ qr: entryQr, deviceIdentifier: device.deviceIdentifier, deviceSecret: rawSecret }, officer.id, "127.0.0.1");

    const { qr: exitQr } = await getOrCreateExitCode(device.deviceIdentifier, rawSecret, officer.id, "127.0.0.1");

    const CONCURRENCY = 10;
    const outcomes = await Promise.allSettled(
      Array.from({ length: CONCURRENCY }, () => verifyExit({ qr: exitQr }, student.userId, student.id, "127.0.0.1"))
    );

    const succeeded = outcomes.filter((o) => o.status === "fulfilled");
    const rejected = outcomes.filter((o) => o.status === "rejected");
    expect(succeeded).toHaveLength(1);
    expect(rejected).toHaveLength(CONCURRENCY - 1);
    for (const r of rejected) {
      if (r.status !== "rejected") continue;
      expect(r.reason).toMatchObject({ code: "ALREADY_OUTSIDE" });
    }

    const exitEvents = await prisma.accessEvent.findMany({ where: { studentId: student.id, eventType: "EXIT" } });
    expect(exitEvents).toHaveLength(1);

    const presence = await prisma.studentPresence.findUnique({ where: { studentId: student.id } });
    expect(presence?.status).toBe("OUTSIDE");
  });

  it("the same permanent exit code correctly and independently exits two different students scanning concurrently", async () => {
    const officer = await createStaffUser();
    const gate = await createGate();
    const { device, rawSecret } = await createDevice(gate.id, officer.id);
    const studentA = await createStudent();
    const studentB = await createStudent();

    for (const s of [studentA, studentB]) {
      const { qr } = await createStudentQrSession(s.id, "127.0.0.1");
      await verifyScan({ qr, deviceIdentifier: device.deviceIdentifier, deviceSecret: rawSecret }, officer.id, "127.0.0.1");
    }

    const { qr: exitQr } = await getOrCreateExitCode(device.deviceIdentifier, rawSecret, officer.id, "127.0.0.1");

    const outcomes = await Promise.allSettled([
      verifyExit({ qr: exitQr }, studentA.userId, studentA.id, "127.0.0.1"),
      verifyExit({ qr: exitQr }, studentB.userId, studentB.id, "127.0.0.1"),
    ]);

    expect(outcomes.every((o) => o.status === "fulfilled")).toBe(true);

    const [presenceA, presenceB] = await Promise.all([
      prisma.studentPresence.findUnique({ where: { studentId: studentA.id } }),
      prisma.studentPresence.findUnique({ where: { studentId: studentB.id } }),
    ]);
    expect(presenceA?.status).toBe("OUTSIDE");
    expect(presenceB?.status).toBe("OUTSIDE");
  });

  it("two simultaneous scan-verification calls never both succeed against a device that is concurrently disabled", async () => {
    const officer = await createStaffUser();
    const gate = await createGate();
    const { device, rawSecret } = await createDevice(gate.id, officer.id);
    const student = await createStudent();
    const { qr } = await createStudentQrSession(student.id, "127.0.0.1");
    const scanInput = { qr, deviceIdentifier: device.deviceIdentifier, deviceSecret: rawSecret };

    // The racing verify call may legitimately land on either side of the
    // disable — either it fully completes first (succeeds) or the disable wins
    // the race (rejected as DEVICE_UNAUTHORIZED). Both are correct; what must
    // never happen is an unhandled crash or a verification that succeeds
    // *after* the device reads as disabled.
    const [firstAttempt] = await Promise.allSettled([
      verifyScan(scanInput, officer.id, "127.0.0.1"),
      prisma.device.update({ where: { id: device.id }, data: { active: false } }),
    ]);
    if (firstAttempt.status === "rejected") {
      expect(firstAttempt.reason).toMatchObject({ code: "DEVICE_UNAUTHORIZED" });
    }

    // Regardless of ordering, the device is now disabled — no further scans may be verified.
    const { qr: qr2 } = await createStudentQrSession(student.id, "127.0.0.1");
    await expect(
      verifyScan({ qr: qr2, deviceIdentifier: device.deviceIdentifier, deviceSecret: rawSecret }, officer.id, "127.0.0.1")
    ).rejects.toMatchObject({ code: "DEVICE_UNAUTHORIZED" });
  });
});
