import { NextRequest, NextResponse } from "next/server";
import { requireSessionWithRole } from "@/server/middleware/auth";
import { withErrorHandling } from "@/server/lib/apiHandler";
import { getClientIp } from "@/server/middleware/rateLimit";
import { AppError } from "@/server/lib/errors";
import { revokeOwnSession } from "@/server/modules/security/sessions.service";

// Every route here depends on the session cookie / DB state — never statically cached.
export const dynamic = "force-dynamic";

interface Params {
  params: { id: string };
}

// A student cancels a QR session they generated themselves, before anyone
// scans it (e.g. generated by mistake, or they're no longer at the gate).
export const POST = withErrorHandling(async (req: NextRequest, { params }: Params) => {
  const session = await requireSessionWithRole(req, "STUDENT");
  if (!session.studentId) {
    throw new AppError("STUDENT_NOT_FOUND", "No student profile is linked to this account.");
  }
  const ip = getClientIp(req.headers);
  const result = await revokeOwnSession(params.id, session.sub, session.studentId, ip);
  return NextResponse.json({ success: true, session: result });
});
